spring.application.name=spring-ecomm

spring.security.user.name=admin
spring.security.user.password=password

# --- DB Config -----
spring.datasource.url=jdbc:h2:mem:userDB
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=admin
spring.datasource.password=admin
spring.h2.console.enabled=true

# --- jwt config ----
spring.app.jwtSecret=kxtzAL6nRnTJGQh6ZW/KBXybxtOyWClwj3zxhWOy1zKKHPar/aq2Z66ltV+aD8sX
spring.app.jwtExpirationMs=3600000


